services:
  prod:
    container_name: app-hotel-parking-prod
    image: app-hotel-parking-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: npm run start